---
    - name: Check if user is using RHEL
      assert:
        that: "ansible_distribution == 'RedHat'"
    
    - name: Enable Repos Specific to OCP 3.9
      command: subscription-manager repos --enable="rhel-7-server-ose-3.9-rpms" --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-fast-datapath-rpms" --enable="rhel-7-server-ansible-2.4-rpms"
      
    - name: Update all hosts
      yum:
        name: '*'
        state: latest
        
    - name: Installing Dependencies for Openshift Container Platform
      yum:
        name:
          - wget
          - git
          - net-tools
          - bind-utils
          - iptables-services
          - bridge-utils
          - sos
          - psacct
          - atomic-openshift-utils
          - docker
          - NetworkManager
    
    - name: Open ports required for dnsmasq and dns for OCP
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - 8053/udp
        - 8053/tcp
        - 53/udp
        - 53/tcp

    - name: Creating Docker Storage Configuration File
      copy:
        src: docker-storage-setup
        dest: "{{ dockercfg }}"
        owner: root
        group: root
        mode: 755
        
    - name: check if docker-vg exists
      stat:
        path: "{{ item }}"
        register: dockervg_result
      with_items:
        - "/dev/docker-vg"
        
    - name: Creating Docker thing Pools and Configuring storage for docker Containers
      command: "docker-storage-setup"
      when: dockervg_result.stat.exists == False
        
    - name: Enable docker service
      systemd:
        name: docker
        state: started
        enabled: True
